<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Moya\新文件夹\**" />
    <EmbeddedResource Remove="Moya\新文件夹\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Moya\Images\Cards\moya_block.png" />
    <Content Include="Moya\Images\Charui\big_energy.png" />
    <Content Include="Moya\Images\Charui\character_icon_char_name.png" />
    <Content Include="Moya\Images\Charui\char_select_char_name.png" />
    <Content Include="Moya\Images\Charui\char_select_char_name_locked.png" />
    <Content Include="Moya\Images\Charui\map_marker_char_name.png" />
    <Content Include="Moya\Images\Charui\text_energy.png" />
    <Content Include="Moya\localization\zhs\cards.json" />
    <Content Include="Moya\localization\zhs\characters.json" />
    <Content Include="moya\localization\zhs\monsters.json" />
    <Content Include="Moya\localization\zhs\powers.json" />
    <Content Include="moya\localization\zhs\relics.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>D:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BaseLib">
      <HintPath>..\..\SteamLibrary\steamapps\workshop\content\2868840\3737335127\BaseLib\BaseLib.dll</HintPath>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>D:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\GodotSharp.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>D:\SteamLibrary\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
    </Reference>
    <Reference Include="Watcher">
      <HintPath>..\..\SteamLibrary\steamapps\common\Slay the Spire 2\mods\观者（BravoBon）\Watcher.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Moya\Images\Cards\card.png.import" />
    <None Include="Moya\Images\Charui\big_energy.png.import" />
    <None Include="Moya\Images\Charui\character_icon_char_name.png.import" />
    <None Include="Moya\Images\Charui\char_select_char_name.png.import" />
    <None Include="Moya\Images\Charui\char_select_char_name_locked.png.import" />
    <None Include="Moya\Images\Charui\map_marker_char_name.png.import" />
    <None Include="Moya\Images\Charui\text_energy.png.import" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.9" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Moya\Images\Powers\Big\" />
    <Folder Include="Moya\Images\Relics\" />
  </ItemGroup>
</Project>